MetaSchema = dict(type="object",
                  additionalProperties=True,
                  title="Metadata",
                  required=["name", "data"],
                  properties=dict(name=dict(type="string",
                                            title="Name",
                                            default="name"),
                                  data=dict(type="string",
                                            title="Data",
                                            default="data")))

LinkSchema = dict(type="object",
                  additionalProperties=True,
                  title="Link",
                  required=["name", "icon", "path", "text"],
                  properties=dict(name=dict(type="string",
                                            title="Link Name",
                                            default="name",
                                            examples=["home"]),
                                  icon=dict(type="string",
                                            title="Link Icon",
                                            default="icon",
                                            examples=["fa fa-home"]),
                                  path=dict(type="string",
                                            title="Link Path",
                                            default="path",
                                            examples=["/"]),
                                  text=dict(type="string",
                                            title="Link Label",
                                            default="text",
                                            examples=["Home"])))

MenuSchema = dict(type="object",
                  additionalProperties=True,
                  title="Menu",
                  required=["name", "children"],
                  properties=dict(name=dict(type="string",
                                            title="Menu Name",
                                            default="name",
                                            examples=["main"]),
                                  children=dict(type="array",
                                                title="Menu Items",
                                                items={"$ref": "#/definitions/menu_item"})),
                  definitions=dict(menu_item=dict(type="object",
                                                  title="Menu Item",
                                                  required=["name"],
                                                  properties=dict(name=dict(type="string",
                                                                            title="MenuItem Name",
                                                                            default="name",
                                                                            examples=["main"]),
                                                                  children=dict(type="array",
                                                                                title="MenuItem Children",
                                                                                items=dict(type="string"))))))

ItemSchema = dict(type="object",
                  additionalProperties=True,
                  title="Item",
                  required=["name", "title", "subtitle", "contents"],
                  properties=dict(name=dict(type="string",
                                            title="Iteme Name",
                                            default="name",
                                            examples=["main"]),
                                  title=dict(type="string",
                                             title="Item Title",
                                             default="title",
                                             examples=["Title"]),
                                  subtitle=dict(type="string",
                                                title="Item Subtitle",
                                                default="Subtitle",
                                                examples=["Subtitle"]),
                                  contents=dict(type="array",
                                                title="Node Contents",
                                                items=dict(type="string"))))

NodeSchema = dict(type="object",
                  additionalProperties=True,
                  title="Node",
                  required=["name", "title", "subtitle", "contents"],
                  properties=dict(name=dict(type="string",
                                            title="Node Name",
                                            default="name",
                                            examples=["main"]),
                                  title=dict(type="string",
                                             title="Node title",
                                             default="title",
                                             examples=["Title"]),
                                  subtitle=dict(type="string",
                                                title="Node Subtitle",
                                                default="Subtitle",
                                                examples=["Subtitle"]),
                                  metas=dict(type="object",
                                             title="Node Metadata"),
                                  template=dict(type="string",
                                                title="Node Template",
                                                default="Subtitle",
                                                examples=["Subtitle"]),
                                  keywords=dict(type="string",
                                                title="Node Keywords",
                                                default="keyword",
                                                examples=["keyword"]),
                                  contents=dict(type="array",
                                                title="Node Contents",
                                                items=dict(type="string"))),
                  children=dict(type="array",
                                title="Page Children",
                                items={"$ref": "#/definitions/item"}),
                  definitions=dict(node=dict(type="object",
                                             title="Item",
                                             required=["name", "title", "subtitle", "contents"],
                                             properties=dict(name=dict(type="string",
                                                                       title="Item Name",
                                                                       default="name",
                                                                       examples=["main"]),
                                                             title=dict(type="string",
                                                                        title="Item Title",
                                                                        default="Title",
                                                                        examples=["Title"]),
                                                             subtitle=dict(type="string",
                                                                           title="Item Subtitle",
                                                                           default="Subtitle",
                                                                           examples=["Subtitle"]),
                                                             metas=dict(type="object",
                                                                        title="Node Metadata"),
                                                             contents=dict(type="array",
                                                                           title="Item Page Contents",
                                                                           items=dict(type="string"))))))

PageSchema = dict(type="object",
                  additionalProperties=True,
                  title="Page",
                  required=["name", "title", "template", "keywords", "subtitle", "contents"],
                  properties=dict(title=dict(type="string",
                                             title="Page Title",
                                             default="title",
                                             examples=["Title"]),
                                  subtitle=dict(type="string",
                                                title="Page Subtitle",
                                                default="Subtitle",
                                                examples=["Subtitle"]),
                                  metas=dict(type="object",
                                             title="Node Metadata"),
                                  template=dict(type="string",
                                                title="Page Template",
                                                default="keyword",
                                                examples=["flask"]),
                                  keywords=dict(type="string",
                                                title="Page Keywords",
                                                default="keyword",
                                                examples=["Flask"]),
                                  contents=dict(type="array",
                                                title="Page Contents",
                                                items=dict(type="string")),
                                  children=dict(type="array",
                                                title="Page Children",
                                                items={"$ref": "#/definitions/node"}),
                                  nodes=dict(type="array",
                                             title="Nodes",
                                             items=dict(type="string"))),
                  definitions=dict(node=dict(type="object",
                                             title="Node",
                                             required=["name", "title", "subtitle", "contents"],
                                             properties=dict(name=dict(type="string",
                                                                       title="Node Name",
                                                                       default="name",
                                                                       examples=["main"]),
                                                             title=dict(type="string",
                                                                        title="Node Title",
                                                                        default="Title",
                                                                        examples=["Title"]),
                                                             subtitle=dict(type="string",
                                                                           title="Node Subtitle",
                                                                           default="Subtitle",
                                                                           examples=["Subtitle"]),
                                                             metas=dict(type="object",
                                                                        title="Node Metadata"),
                                                             contents=dict(type="array",
                                                                           title="Node Page Contents",
                                                                           items=dict(type="string"))))))

SiteSchema = dict(type="object",
                  additionalProperties=True,
                  title="Site",
                  required=["name"],
                  properties=dict(name=dict(type="string",
                                            title="Site Name",
                                            default="localhost"),
                                  hosts=dict(type="string",
                                             title="Site Hosts",
                                             default="localhost"),
                                  product=dict(type="string",
                                               title="Site Product",
                                               default="product"),
                                  version=dict(type="string",
                                               title="Site Version",
                                               default="version"),
                                  authors=dict(type="string",
                                               title="Site Authors",
                                               default="authors"),
                                  license=dict(type="string",
                                               title="Site License",
                                               default="license"),
                                  scripts=dict(type="string",
                                               title="Site Scripts"),
                                  styles=dict(type="string",
                                              title="Site Styles"),
                                  seo={"type": "object",
                                       "$ref": "#/definitions/seo"},
                                  brand={"type": "object",
                                         "$ref": "#/definitions/brand"}),
                  definitions=dict(brand=dict(type="object",
                                              title="Site Brand",
                                              required=["icon", "text"],
                                              properties=dict(text=dict(type="string",
                                                                        title="Site Brand Label",
                                                                        default="brand"),
                                                              icon=dict(type="string",
                                                                        title="Site Brand Icon",
                                                                        default="fa fa-home"),
                                                              image_url=dict(type="string",
                                                                             title="Site Brand Image URL"))),
                                   seo=dict(type="object",
                                            title="Site SEO",
                                            required=["title", "favicon", "keywords"],
                                            properties=dict(title=dict(type="string",
                                                                       title="Site SEO Title",
                                                                       default="website",
                                                                       examples=["website"]),
                                                            description=dict(type="string",
                                                                             title="Site SEO Description",
                                                                             default="Description",
                                                                             examples=["..."]),
                                                            favicon=dict(type="string",
                                                                         title="Site SEO Favorite Icon",
                                                                         default="Subtitle",
                                                                         examples=["Subtitle"]),
                                                            keywords=dict(type="string",
                                                                          title="Site SEO Keywords",
                                                                          default="Subtitle",
                                                                          examples=["Subtitle"]),
                                                            robots=dict(type="string",
                                                                        title="SEO Robots",
                                                                        items=dict(type="string"))))))
