- name: service1
  title: Service title 1
  description: Just a short description
  category: Category1
  image_url: /assets/images/services/service1.png
- name: service2
  title: Service title 2
  description: Just a short description
  category: Category2
  image_url: /assets/images/services/service2.png
